(cl:defpackage location_service-srv
  (:use )
  (:export
   "DELETELOCATION"
   "<DELETELOCATION-REQUEST>"
   "DELETELOCATION-REQUEST"
   "<DELETELOCATION-RESPONSE>"
   "DELETELOCATION-RESPONSE"
   "GETLOCATION"
   "<GETLOCATION-REQUEST>"
   "GETLOCATION-REQUEST"
   "<GETLOCATION-RESPONSE>"
   "GETLOCATION-RESPONSE"
   "STORELOCATION"
   "<STORELOCATION-REQUEST>"
   "STORELOCATION-REQUEST"
   "<STORELOCATION-RESPONSE>"
   "STORELOCATION-RESPONSE"
  ))

