// Generated by gencpp from file replan_topological_graph_action/replanAction.msg
// DO NOT EDIT!


#ifndef REPLAN_TOPOLOGICAL_GRAPH_ACTION_MESSAGE_REPLANACTION_H
#define REPLAN_TOPOLOGICAL_GRAPH_ACTION_MESSAGE_REPLANACTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <replan_topological_graph_action/replanActionGoal.h>
#include <replan_topological_graph_action/replanActionResult.h>
#include <replan_topological_graph_action/replanActionFeedback.h>

namespace replan_topological_graph_action
{
template <class ContainerAllocator>
struct replanAction_
{
  typedef replanAction_<ContainerAllocator> Type;

  replanAction_()
    : action_goal()
    , action_result()
    , action_feedback()  {
    }
  replanAction_(const ContainerAllocator& _alloc)
    : action_goal(_alloc)
    , action_result(_alloc)
    , action_feedback(_alloc)  {
  (void)_alloc;
    }



   typedef  ::replan_topological_graph_action::replanActionGoal_<ContainerAllocator>  _action_goal_type;
  _action_goal_type action_goal;

   typedef  ::replan_topological_graph_action::replanActionResult_<ContainerAllocator>  _action_result_type;
  _action_result_type action_result;

   typedef  ::replan_topological_graph_action::replanActionFeedback_<ContainerAllocator>  _action_feedback_type;
  _action_feedback_type action_feedback;




  typedef boost::shared_ptr< ::replan_topological_graph_action::replanAction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::replan_topological_graph_action::replanAction_<ContainerAllocator> const> ConstPtr;

}; // struct replanAction_

typedef ::replan_topological_graph_action::replanAction_<std::allocator<void> > replanAction;

typedef boost::shared_ptr< ::replan_topological_graph_action::replanAction > replanActionPtr;
typedef boost::shared_ptr< ::replan_topological_graph_action::replanAction const> replanActionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::replan_topological_graph_action::replanAction_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::replan_topological_graph_action::replanAction_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace replan_topological_graph_action

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'replan_topological_graph_action': ['/home/francesco/planning_ws/devel/share/replan_topological_graph_action/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::replan_topological_graph_action::replanAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::replan_topological_graph_action::replanAction_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::replan_topological_graph_action::replanAction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::replan_topological_graph_action::replanAction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::replan_topological_graph_action::replanAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::replan_topological_graph_action::replanAction_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::replan_topological_graph_action::replanAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d9039de82fb2863f79151c939d3fdecc";
  }

  static const char* value(const ::replan_topological_graph_action::replanAction_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd9039de82fb2863fULL;
  static const uint64_t static_value2 = 0x79151c939d3fdeccULL;
};

template<class ContainerAllocator>
struct DataType< ::replan_topological_graph_action::replanAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "replan_topological_graph_action/replanAction";
  }

  static const char* value(const ::replan_topological_graph_action::replanAction_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::replan_topological_graph_action::replanAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
replanActionGoal action_goal\n\
replanActionResult action_result\n\
replanActionFeedback action_feedback\n\
\n\
================================================================================\n\
MSG: replan_topological_graph_action/replanActionGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalID goal_id\n\
replanGoal goal\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalID\n\
# The stamp should store the time at which this goal was requested.\n\
# It is used by an action server when it tries to preempt all\n\
# goals that were requested before a certain time\n\
time stamp\n\
\n\
# The id provides a way to associate feedback and\n\
# result message with specific goal requests. The id\n\
# specified must be unique.\n\
string id\n\
\n\
\n\
================================================================================\n\
MSG: replan_topological_graph_action/replanGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal definition\n\
float64[4] goal\n\
\n\
================================================================================\n\
MSG: replan_topological_graph_action/replanActionResult\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalStatus status\n\
replanResult result\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalStatus\n\
GoalID goal_id\n\
uint8 status\n\
uint8 PENDING         = 0   # The goal has yet to be processed by the action server\n\
uint8 ACTIVE          = 1   # The goal is currently being processed by the action server\n\
uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing\n\
                            #   and has since completed its execution (Terminal State)\n\
uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)\n\
uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due\n\
                            #    to some failure (Terminal State)\n\
uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,\n\
                            #    because the goal was unattainable or invalid (Terminal State)\n\
uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing\n\
                            #    and has not yet completed execution\n\
uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,\n\
                            #    but the action server has not yet confirmed that the goal is canceled\n\
uint8 RECALLED        = 8   # The goal received a cancel request before it started executing\n\
                            #    and was successfully cancelled (Terminal State)\n\
uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be\n\
                            #    sent over the wire by an action server\n\
\n\
#Allow for the user to associate a string with GoalStatus for debugging\n\
string text\n\
\n\
\n\
================================================================================\n\
MSG: replan_topological_graph_action/replanResult\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#result definition\n\
float64[4] goal\n\
\n\
================================================================================\n\
MSG: replan_topological_graph_action/replanActionFeedback\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalStatus status\n\
replanFeedback feedback\n\
\n\
================================================================================\n\
MSG: replan_topological_graph_action/replanFeedback\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#feedback definition\n\
float64[4] goal\n\
\n\
";
  }

  static const char* value(const ::replan_topological_graph_action::replanAction_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::replan_topological_graph_action::replanAction_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action_goal);
      stream.next(m.action_result);
      stream.next(m.action_feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct replanAction_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::replan_topological_graph_action::replanAction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::replan_topological_graph_action::replanAction_<ContainerAllocator>& v)
  {
    s << indent << "action_goal: ";
    s << std::endl;
    Printer< ::replan_topological_graph_action::replanActionGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.action_goal);
    s << indent << "action_result: ";
    s << std::endl;
    Printer< ::replan_topological_graph_action::replanActionResult_<ContainerAllocator> >::stream(s, indent + "  ", v.action_result);
    s << indent << "action_feedback: ";
    s << std::endl;
    Printer< ::replan_topological_graph_action::replanActionFeedback_<ContainerAllocator> >::stream(s, indent + "  ", v.action_feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REPLAN_TOPOLOGICAL_GRAPH_ACTION_MESSAGE_REPLANACTION_H
