// Generated by gencpp from file pddl_msgs/PDDLObject.msg
// DO NOT EDIT!


#ifndef PDDL_MSGS_MESSAGE_PDDLOBJECT_H
#define PDDL_MSGS_MESSAGE_PDDLOBJECT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pddl_msgs
{
template <class ContainerAllocator>
struct PDDLObject_
{
  typedef PDDLObject_<ContainerAllocator> Type;

  PDDLObject_()
    : name()
    , type()  {
    }
  PDDLObject_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , type(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _type_type;
  _type_type type;




  typedef boost::shared_ptr< ::pddl_msgs::PDDLObject_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pddl_msgs::PDDLObject_<ContainerAllocator> const> ConstPtr;

}; // struct PDDLObject_

typedef ::pddl_msgs::PDDLObject_<std::allocator<void> > PDDLObject;

typedef boost::shared_ptr< ::pddl_msgs::PDDLObject > PDDLObjectPtr;
typedef boost::shared_ptr< ::pddl_msgs::PDDLObject const> PDDLObjectConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pddl_msgs::PDDLObject_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pddl_msgs::PDDLObject_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pddl_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'pddl_msgs': ['/home/francesco/planning_ws/devel/share/pddl_msgs/msg', '/home/francesco/planning_ws/src/spqr_planning_and_reasoning/jsk_planning/pddl/pddl_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pddl_msgs::PDDLObject_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pddl_msgs::PDDLObject_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pddl_msgs::PDDLObject_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pddl_msgs::PDDLObject_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pddl_msgs::PDDLObject_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pddl_msgs::PDDLObject_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pddl_msgs::PDDLObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8f11915b22b276d2fb5587b35400289d";
  }

  static const char* value(const ::pddl_msgs::PDDLObject_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8f11915b22b276d2ULL;
  static const uint64_t static_value2 = 0xfb5587b35400289dULL;
};

template<class ContainerAllocator>
struct DataType< ::pddl_msgs::PDDLObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pddl_msgs/PDDLObject";
  }

  static const char* value(const ::pddl_msgs::PDDLObject_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pddl_msgs::PDDLObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# definition of PDDLObject\n\
string name\n\
string type\n\
";
  }

  static const char* value(const ::pddl_msgs::PDDLObject_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pddl_msgs::PDDLObject_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PDDLObject_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pddl_msgs::PDDLObject_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pddl_msgs::PDDLObject_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PDDL_MSGS_MESSAGE_PDDLOBJECT_H
