(cl:defpackage master_plan_action-msg
  (:use )
  (:export
   "<MASTERACTION>"
   "MASTERACTION"
   "<MASTERACTIONFEEDBACK>"
   "MASTERACTIONFEEDBACK"
   "<MASTERACTIONGOAL>"
   "MASTERACTIONGOAL"
   "<MASTERACTIONRESULT>"
   "MASTERACTIONRESULT"
   "<MASTERFEEDBACK>"
   "MASTERFEEDBACK"
   "<MASTERGOAL>"
   "MASTERGOAL"
   "<MASTERRESULT>"
   "MASTERRESULT"
  ))

