; Auto-generated. Do not edit!


(cl:in-package master_plan_action-msg)


;//! \htmlinclude masterResult.msg.html

(cl:defclass <masterResult> (roslisp-msg-protocol:ros-message)
  ((goal
    :reader goal
    :initarg :goal
    :type cl:float
    :initform 0.0))
)

(cl:defclass masterResult (<masterResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <masterResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'masterResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name master_plan_action-msg:<masterResult> is deprecated: use master_plan_action-msg:masterResult instead.")))

(cl:ensure-generic-function 'goal-val :lambda-list '(m))
(cl:defmethod goal-val ((m <masterResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader master_plan_action-msg:goal-val is deprecated.  Use master_plan_action-msg:goal instead.")
  (goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <masterResult>) ostream)
  "Serializes a message object of type '<masterResult>"
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'goal))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <masterResult>) istream)
  "Deserializes a message object of type '<masterResult>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'goal) (roslisp-utils:decode-double-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<masterResult>)))
  "Returns string type for a message object of type '<masterResult>"
  "master_plan_action/masterResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'masterResult)))
  "Returns string type for a message object of type 'masterResult"
  "master_plan_action/masterResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<masterResult>)))
  "Returns md5sum for a message object of type '<masterResult>"
  "96f1fc969cebfe9056357b5db1aa501e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'masterResult)))
  "Returns md5sum for a message object of type 'masterResult"
  "96f1fc969cebfe9056357b5db1aa501e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<masterResult>)))
  "Returns full string definition for message of type '<masterResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%float64 goal~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'masterResult)))
  "Returns full string definition for message of type 'masterResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%float64 goal~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <masterResult>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <masterResult>))
  "Converts a ROS message object to a list"
  (cl:list 'masterResult
    (cl:cons ':goal (goal msg))
))
