// Generated by gencpp from file location_service/DeleteLocationRequest.msg
// DO NOT EDIT!


#ifndef LOCATION_SERVICE_MESSAGE_DELETELOCATIONREQUEST_H
#define LOCATION_SERVICE_MESSAGE_DELETELOCATIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace location_service
{
template <class ContainerAllocator>
struct DeleteLocationRequest_
{
  typedef DeleteLocationRequest_<ContainerAllocator> Type;

  DeleteLocationRequest_()
    : name()  {
    }
  DeleteLocationRequest_(const ContainerAllocator& _alloc)
    : name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;




  typedef boost::shared_ptr< ::location_service::DeleteLocationRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::location_service::DeleteLocationRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DeleteLocationRequest_

typedef ::location_service::DeleteLocationRequest_<std::allocator<void> > DeleteLocationRequest;

typedef boost::shared_ptr< ::location_service::DeleteLocationRequest > DeleteLocationRequestPtr;
typedef boost::shared_ptr< ::location_service::DeleteLocationRequest const> DeleteLocationRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::location_service::DeleteLocationRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::location_service::DeleteLocationRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace location_service

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'location_service': ['/home/francesco/planning_ws/src/location_service/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::location_service::DeleteLocationRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::location_service::DeleteLocationRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::location_service::DeleteLocationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::location_service::DeleteLocationRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::location_service::DeleteLocationRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::location_service::DeleteLocationRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::location_service::DeleteLocationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c1f3d28f1b044c871e6eff2e9fc3c667";
  }

  static const char* value(const ::location_service::DeleteLocationRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc1f3d28f1b044c87ULL;
  static const uint64_t static_value2 = 0x1e6eff2e9fc3c667ULL;
};

template<class ContainerAllocator>
struct DataType< ::location_service::DeleteLocationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "location_service/DeleteLocationRequest";
  }

  static const char* value(const ::location_service::DeleteLocationRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::location_service::DeleteLocationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string  name\n\
";
  }

  static const char* value(const ::location_service::DeleteLocationRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::location_service::DeleteLocationRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DeleteLocationRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::location_service::DeleteLocationRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::location_service::DeleteLocationRequest_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LOCATION_SERVICE_MESSAGE_DELETELOCATIONREQUEST_H
