// Generated by gencpp from file location_service/DeleteLocationResponse.msg
// DO NOT EDIT!


#ifndef LOCATION_SERVICE_MESSAGE_DELETELOCATIONRESPONSE_H
#define LOCATION_SERVICE_MESSAGE_DELETELOCATIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace location_service
{
template <class ContainerAllocator>
struct DeleteLocationResponse_
{
  typedef DeleteLocationResponse_<ContainerAllocator> Type;

  DeleteLocationResponse_()
    : success(false)
    , reason()  {
    }
  DeleteLocationResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , reason(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _reason_type;
  _reason_type reason;




  typedef boost::shared_ptr< ::location_service::DeleteLocationResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::location_service::DeleteLocationResponse_<ContainerAllocator> const> ConstPtr;

}; // struct DeleteLocationResponse_

typedef ::location_service::DeleteLocationResponse_<std::allocator<void> > DeleteLocationResponse;

typedef boost::shared_ptr< ::location_service::DeleteLocationResponse > DeleteLocationResponsePtr;
typedef boost::shared_ptr< ::location_service::DeleteLocationResponse const> DeleteLocationResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::location_service::DeleteLocationResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::location_service::DeleteLocationResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace location_service

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'location_service': ['/home/francesco/planning_ws/src/location_service/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::location_service::DeleteLocationResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::location_service::DeleteLocationResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::location_service::DeleteLocationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::location_service::DeleteLocationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::location_service::DeleteLocationResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::location_service::DeleteLocationResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::location_service::DeleteLocationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a4d50a34d34f18de48e2436ff1472594";
  }

  static const char* value(const ::location_service::DeleteLocationResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa4d50a34d34f18deULL;
  static const uint64_t static_value2 = 0x48e2436ff1472594ULL;
};

template<class ContainerAllocator>
struct DataType< ::location_service::DeleteLocationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "location_service/DeleteLocationResponse";
  }

  static const char* value(const ::location_service::DeleteLocationResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::location_service::DeleteLocationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool  success\n\
string  reason\n\
\n\
";
  }

  static const char* value(const ::location_service::DeleteLocationResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::location_service::DeleteLocationResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.reason);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DeleteLocationResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::location_service::DeleteLocationResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::location_service::DeleteLocationResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "reason: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.reason);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LOCATION_SERVICE_MESSAGE_DELETELOCATIONRESPONSE_H
