// Generated by gencpp from file location_service/DeleteLocation.msg
// DO NOT EDIT!


#ifndef LOCATION_SERVICE_MESSAGE_DELETELOCATION_H
#define LOCATION_SERVICE_MESSAGE_DELETELOCATION_H

#include <ros/service_traits.h>


#include <location_service/DeleteLocationRequest.h>
#include <location_service/DeleteLocationResponse.h>


namespace location_service
{

struct DeleteLocation
{

typedef DeleteLocationRequest Request;
typedef DeleteLocationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DeleteLocation
} // namespace location_service


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::location_service::DeleteLocation > {
  static const char* value()
  {
    return "d0a9c8b4beae30145a913b9f2a6cd3ab";
  }

  static const char* value(const ::location_service::DeleteLocation&) { return value(); }
};

template<>
struct DataType< ::location_service::DeleteLocation > {
  static const char* value()
  {
    return "location_service/DeleteLocation";
  }

  static const char* value(const ::location_service::DeleteLocation&) { return value(); }
};


// service_traits::MD5Sum< ::location_service::DeleteLocationRequest> should match 
// service_traits::MD5Sum< ::location_service::DeleteLocation > 
template<>
struct MD5Sum< ::location_service::DeleteLocationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::location_service::DeleteLocation >::value();
  }
  static const char* value(const ::location_service::DeleteLocationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::location_service::DeleteLocationRequest> should match 
// service_traits::DataType< ::location_service::DeleteLocation > 
template<>
struct DataType< ::location_service::DeleteLocationRequest>
{
  static const char* value()
  {
    return DataType< ::location_service::DeleteLocation >::value();
  }
  static const char* value(const ::location_service::DeleteLocationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::location_service::DeleteLocationResponse> should match 
// service_traits::MD5Sum< ::location_service::DeleteLocation > 
template<>
struct MD5Sum< ::location_service::DeleteLocationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::location_service::DeleteLocation >::value();
  }
  static const char* value(const ::location_service::DeleteLocationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::location_service::DeleteLocationResponse> should match 
// service_traits::DataType< ::location_service::DeleteLocation > 
template<>
struct DataType< ::location_service::DeleteLocationResponse>
{
  static const char* value()
  {
    return DataType< ::location_service::DeleteLocation >::value();
  }
  static const char* value(const ::location_service::DeleteLocationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LOCATION_SERVICE_MESSAGE_DELETELOCATION_H
