// Generated by gencpp from file location_service/StoreLocation.msg
// DO NOT EDIT!


#ifndef LOCATION_SERVICE_MESSAGE_STORELOCATION_H
#define LOCATION_SERVICE_MESSAGE_STORELOCATION_H

#include <ros/service_traits.h>


#include <location_service/StoreLocationRequest.h>
#include <location_service/StoreLocationResponse.h>


namespace location_service
{

struct StoreLocation
{

typedef StoreLocationRequest Request;
typedef StoreLocationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StoreLocation
} // namespace location_service


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::location_service::StoreLocation > {
  static const char* value()
  {
    return "d0a9c8b4beae30145a913b9f2a6cd3ab";
  }

  static const char* value(const ::location_service::StoreLocation&) { return value(); }
};

template<>
struct DataType< ::location_service::StoreLocation > {
  static const char* value()
  {
    return "location_service/StoreLocation";
  }

  static const char* value(const ::location_service::StoreLocation&) { return value(); }
};


// service_traits::MD5Sum< ::location_service::StoreLocationRequest> should match 
// service_traits::MD5Sum< ::location_service::StoreLocation > 
template<>
struct MD5Sum< ::location_service::StoreLocationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::location_service::StoreLocation >::value();
  }
  static const char* value(const ::location_service::StoreLocationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::location_service::StoreLocationRequest> should match 
// service_traits::DataType< ::location_service::StoreLocation > 
template<>
struct DataType< ::location_service::StoreLocationRequest>
{
  static const char* value()
  {
    return DataType< ::location_service::StoreLocation >::value();
  }
  static const char* value(const ::location_service::StoreLocationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::location_service::StoreLocationResponse> should match 
// service_traits::MD5Sum< ::location_service::StoreLocation > 
template<>
struct MD5Sum< ::location_service::StoreLocationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::location_service::StoreLocation >::value();
  }
  static const char* value(const ::location_service::StoreLocationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::location_service::StoreLocationResponse> should match 
// service_traits::DataType< ::location_service::StoreLocation > 
template<>
struct DataType< ::location_service::StoreLocationResponse>
{
  static const char* value()
  {
    return DataType< ::location_service::StoreLocation >::value();
  }
  static const char* value(const ::location_service::StoreLocationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LOCATION_SERVICE_MESSAGE_STORELOCATION_H
