; Auto-generated. Do not edit!


(cl:in-package pddl_msgs-msg)


;//! \htmlinclude PDDLPlannerFeedback.msg.html

(cl:defclass <PDDLPlannerFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass PDDLPlannerFeedback (<PDDLPlannerFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PDDLPlannerFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PDDLPlannerFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name pddl_msgs-msg:<PDDLPlannerFeedback> is deprecated: use pddl_msgs-msg:PDDLPlannerFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PDDLPlannerFeedback>) ostream)
  "Serializes a message object of type '<PDDLPlannerFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PDDLPlannerFeedback>) istream)
  "Deserializes a message object of type '<PDDLPlannerFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PDDLPlannerFeedback>)))
  "Returns string type for a message object of type '<PDDLPlannerFeedback>"
  "pddl_msgs/PDDLPlannerFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PDDLPlannerFeedback)))
  "Returns string type for a message object of type 'PDDLPlannerFeedback"
  "pddl_msgs/PDDLPlannerFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PDDLPlannerFeedback>)))
  "Returns md5sum for a message object of type '<PDDLPlannerFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PDDLPlannerFeedback)))
  "Returns md5sum for a message object of type 'PDDLPlannerFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PDDLPlannerFeedback>)))
  "Returns full string definition for message of type '<PDDLPlannerFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PDDLPlannerFeedback)))
  "Returns full string definition for message of type 'PDDLPlannerFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PDDLPlannerFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PDDLPlannerFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'PDDLPlannerFeedback
))
