// Generated by gencpp from file spqr_laser_obstacle_detection/flag.msg
// DO NOT EDIT!


#ifndef SPQR_LASER_OBSTACLE_DETECTION_MESSAGE_FLAG_H
#define SPQR_LASER_OBSTACLE_DETECTION_MESSAGE_FLAG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace spqr_laser_obstacle_detection
{
template <class ContainerAllocator>
struct flag_
{
  typedef flag_<ContainerAllocator> Type;

  flag_()
    : detected(false)  {
    }
  flag_(const ContainerAllocator& _alloc)
    : detected(false)  {
  (void)_alloc;
    }



   typedef uint8_t _detected_type;
  _detected_type detected;




  typedef boost::shared_ptr< ::spqr_laser_obstacle_detection::flag_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::spqr_laser_obstacle_detection::flag_<ContainerAllocator> const> ConstPtr;

}; // struct flag_

typedef ::spqr_laser_obstacle_detection::flag_<std::allocator<void> > flag;

typedef boost::shared_ptr< ::spqr_laser_obstacle_detection::flag > flagPtr;
typedef boost::shared_ptr< ::spqr_laser_obstacle_detection::flag const> flagConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::spqr_laser_obstacle_detection::flag_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::spqr_laser_obstacle_detection::flag_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace spqr_laser_obstacle_detection

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'spqr_laser_obstacle_detection': ['/home/francesco/planning_ws/src/spqr_laser_obstacle_detection/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::spqr_laser_obstacle_detection::flag_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::spqr_laser_obstacle_detection::flag_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::spqr_laser_obstacle_detection::flag_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::spqr_laser_obstacle_detection::flag_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::spqr_laser_obstacle_detection::flag_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::spqr_laser_obstacle_detection::flag_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::spqr_laser_obstacle_detection::flag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2d8633c53221d40413712b55b8360a15";
  }

  static const char* value(const ::spqr_laser_obstacle_detection::flag_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2d8633c53221d404ULL;
  static const uint64_t static_value2 = 0x13712b55b8360a15ULL;
};

template<class ContainerAllocator>
struct DataType< ::spqr_laser_obstacle_detection::flag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "spqr_laser_obstacle_detection/flag";
  }

  static const char* value(const ::spqr_laser_obstacle_detection::flag_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::spqr_laser_obstacle_detection::flag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool detected\n\
\n\
";
  }

  static const char* value(const ::spqr_laser_obstacle_detection::flag_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::spqr_laser_obstacle_detection::flag_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.detected);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct flag_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::spqr_laser_obstacle_detection::flag_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::spqr_laser_obstacle_detection::flag_<ContainerAllocator>& v)
  {
    s << indent << "detected: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.detected);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SPQR_LASER_OBSTACLE_DETECTION_MESSAGE_FLAG_H
