; Auto-generated. Do not edit!


(cl:in-package replan_topological_graph_action-msg)


;//! \htmlinclude replanResult.msg.html

(cl:defclass <replanResult> (roslisp-msg-protocol:ros-message)
  ((goal
    :reader goal
    :initarg :goal
    :type (cl:vector cl:float)
   :initform (cl:make-array 4 :element-type 'cl:float :initial-element 0.0)))
)

(cl:defclass replanResult (<replanResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <replanResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'replanResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name replan_topological_graph_action-msg:<replanResult> is deprecated: use replan_topological_graph_action-msg:replanResult instead.")))

(cl:ensure-generic-function 'goal-val :lambda-list '(m))
(cl:defmethod goal-val ((m <replanResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader replan_topological_graph_action-msg:goal-val is deprecated.  Use replan_topological_graph_action-msg:goal instead.")
  (goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <replanResult>) ostream)
  "Serializes a message object of type '<replanResult>"
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'goal))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <replanResult>) istream)
  "Deserializes a message object of type '<replanResult>"
  (cl:setf (cl:slot-value msg 'goal) (cl:make-array 4))
  (cl:let ((vals (cl:slot-value msg 'goal)))
    (cl:dotimes (i 4)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<replanResult>)))
  "Returns string type for a message object of type '<replanResult>"
  "replan_topological_graph_action/replanResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'replanResult)))
  "Returns string type for a message object of type 'replanResult"
  "replan_topological_graph_action/replanResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<replanResult>)))
  "Returns md5sum for a message object of type '<replanResult>"
  "6c0f8a43662c8b5ae9791fef095791e5")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'replanResult)))
  "Returns md5sum for a message object of type 'replanResult"
  "6c0f8a43662c8b5ae9791fef095791e5")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<replanResult>)))
  "Returns full string definition for message of type '<replanResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%float64[4] goal~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'replanResult)))
  "Returns full string definition for message of type 'replanResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%float64[4] goal~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <replanResult>))
  (cl:+ 0
     0 (cl:reduce #'cl:+ (cl:slot-value msg 'goal) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <replanResult>))
  "Converts a ROS message object to a list"
  (cl:list 'replanResult
    (cl:cons ':goal (goal msg))
))
